services:
  - type: web
    name: almaty-traffic
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OWM_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
    autoDeploy: true
